### ISSUE TITLE
Automated Evaluation fails.

### ISSUE THREAD

**Issue by hv10** [rki-daki-fws/forecast-competition#81]
The automated evaluation pipeline is failing for me. 
The files added within my commit seem to be not the responsible ones...
Workflow error:
```bash
/home/runner/work/forecast-competition/forecast-competition/evaluate.py:156: UserWarning: Dates or locations of prediction file submissions/HHI/2022-01-30_seq2seq_LK_cases.parquet don't match ground truth!
```

**Comment by mlbach** [comment]
Thank you for opening the issue! There was a mistake in the logic controlling which files to evaluate. It is fixed now ([commit](https://github.com/rki-daki-fws/forecast-competition/commit/ec2dd55fecc65415e324da1c6aa25d5fb7b24e0f)) and I re-triggered the pipeline.
