### ISSUE TITLE
[Enhancement] Use GitHub Pages to show leaderboard / dashboard / canvas of results.

### ISSUE THREAD

**Issue by hv10** [rki-daki-fws/forecast-competition#87]
Maybe we could implement a github-pages based static page that gets updated automatically and gives a more explorable overview over the results (similar to a dashboard but not neccessarily as strict in structure)

**Comment by mlbach** [comment]
The evaluation report is now available as a github page at [https://rki-daki-fws.github.io/forecast-competition/](https://rki-daki-fws.github.io/forecast-competition/).
Feel free to request more features/visualization/metrics.
